name: Unit Testing
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - '**/*.md'
      - .gitignore
      - ./meta/main.yml
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - .gitignore
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CI_TOKEN }}
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.MAIN_BRANCH }}
          fetch-depth: 0
      
      - name: Run Pytest
      # TODO try this one: https://github.com/pavelzw/pytest-action
        run: |
          pip install pytest pytest-cov
          pytest

  run-action:
    runs-on: ubuntu-latest
    needs:
      - run-unit-tests

    steps:
        - name: Run action
          id: test-action
          uses: ynput/github-query@generate-changelog
          with:
            repo: "ynput/ayon-addon-action-testing"
            date: "2024-08-20T12:03:23Z"
            query_parameters: "body,labels,title"

        - name: Show results
          run: |
            echo "RAW-response: " && echo '${{ steps.test-action.outputs.raw-output }}'
            echo "Labels: " && echo '${{ steps.test-action.outputs.label-list }}'
            echo "Bump-increment: " && echo '${{ steps.test-action.outputs.bump-increment }}'
            echo "Changelog: " && echo '${{ steps.test-action.outputs.changelog-markdown }}'


        - name: Show changelog formatted
          shell: bash
          run: |
            echo "${{ steps.test-action.outputs.changelog-markdown }}"
